version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/site:/sites/demo
    networks:
      - nginx
    
  
networks:
  nginx:
    driver: bridge
